-- 코드를 입력하세요
#SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
#from REST_INFO R
#GROUP BY FOOD_TYPE
#HAVING FAVORITES = MAX(FAVORITES)
#ORDER BY FOOD_TYPE DESC

# SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
# FROM REST_INFO A 
# JOIN (
# SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ) B 
# ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE 
# ORDER BY FOOD_TYPE DESC

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A 
JOIN (
SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
) B 
ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE 
ORDER BY FOOD_TYPE DESC