-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), 
MONTH(SALES_DATE), 
COUNT(DISTINCT(OS.USER_ID)) AS PUCHASED_USERS,
ROUND(
    (COUNT(DISTINCT(OS.USER_ID)))
    /
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1)    
FROM ONLINE_SALE AS OS
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS UI
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);