-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8)) AS '전화번호' FROM USED_GOODS_USER A
JOIN (SELECT WRITER_ID, COUNT(*) AS CNT FROM USED_GOODS_BOARD GROUP BY WRITER_ID) B
ON A.USER_ID = B.WRITER_ID
WHERE B.CNT > 2
ORDER BY A.USER_ID DESC;