-- 코드를 입력하세요
SELECT CAR_ID, 
    CASE
    WHEN ROUND(SUM(DATEDIFF(END_DATE, START_DATE) + 1) / COUNT(*), 1) >= 7 THEN ROUND(SUM(DATEDIFF(END_DATE, START_DATE) + 1) / COUNT(*), 1)
    END AS AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION IS NOT NULL
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC