-- 코드를 입력하세요
SELECT C.USER_ID, C.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES FROM USED_GOODS_USER C
JOIN(
    SELECT WRITER_ID, PRICE, STATUS FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
) B
ON B.WRITER_ID = C.USER_ID
GROUP BY C.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC