-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(C.S) AS TOTAL_SALES FROM BOOK B 
JOIN (
SELECT K.BOOK_ID, SUM(K.SALES) AS S FROM BOOK_SALES K
WHERE K.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK_ID
) C
ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
