-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.DAILY_FEE*30) * (100 - C.DISCOUNT_RATE)*0.01, 0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE
(
    A.CAR_TYPE IN ('SUV', '세단')
)
AND
(
    C.DURATION_TYPE like "%30%"
)
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
AND MAX(B.END_DATE) < '2022-11-01'
ORDER BY FEE DESC, CAR_TYPE, CAR_ID
