-- 코드를 입력하세요
SELECT B.BOOK_ID, C.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE FROM BOOK B
INNER JOIN(
SELECT * FROM AUTHOR A
) C
ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC