-- 코드를 입력하세요
SELECT DISTINCT HISTORY_ID, FEE
FROM
    (SELECT B.HISTORY_ID AS HISTORY_ID,
       DATEDIFF(B.END_DATE, B.START_DATE) AS 'DATE_DIFF',
           CASE
                WHEN (DATEDIFF(B.END_DATE, B.START_DATE)+1 BETWEEN 7 AND 29) AND C.DURATION_TYPE = '7일 이상' THEN ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE)+1) * (100 - C.DISCOUNT_RATE) * 0.01)
                WHEN (DATEDIFF(B.END_DATE, B.START_DATE)+1 BETWEEN 30 AND 89) AND C.DURATION_TYPE = '30일 이상' THEN ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE)+1) * (100 - C.DISCOUNT_RATE) * 0.01)
                WHEN (DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 90) AND C.DURATION_TYPE = '90일 이상' THEN ROUND(A.DAILY_FEE *(DATEDIFF(B.END_DATE, B.START_DATE)+1) * (100 - C.DISCOUNT_RATE) * 0.01)
                WHEN (DATEDIFF(B.END_DATE, B.START_DATE) < 7)  THEN ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE)+1))
                ELSE NULL
           END AS 'FEE'
    FROM CAR_RENTAL_COMPANY_CAR AS A
         LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
         LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_TYPE = '트럭') AS TMP
WHERE FEE IS NOT NULL
ORDER BY FEE DESC, HISTORY_ID DESC